version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
      - image: mongo:4.1.6-xenial
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@5"
      - run:
          name: install-packages
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json"}}
          paths:
            - node_modules
      - run:
          name: test
          command: npm run coverage
      
      - store_artifacts:
          path: coverage

workflows:
  # The workflow version
  version: 2.1
  # A unique name for the workflow
  run_build:
    # The jobs to run in this workflow
    jobs:
      - build